// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgovJur9MCZWODq9qGzAccWWQ6Dph9NTg',
    appId: '1:698836614759:web:715a309799dfabc921dec2',
    messagingSenderId: '698836614759',
    projectId: 'chamgohae123',
    authDomain: 'chamgohae123.firebaseapp.com',
    storageBucket: 'chamgohae123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK1z1QiLxqIASdaZ-hNl0kF5AXi6oBmVg',
    appId: '1:698836614759:android:d8bab8538b4b475a21dec2',
    messagingSenderId: '698836614759',
    projectId: 'chamgohae123',
    storageBucket: 'chamgohae123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw8N3IcegpHGAFI4kbzWcqOqd8Vij9ZAc',
    appId: '1:698836614759:ios:5d52fa621de5bde521dec2',
    messagingSenderId: '698836614759',
    projectId: 'chamgohae123',
    storageBucket: 'chamgohae123.appspot.com',
    iosBundleId: 'com.example.chamgohae1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw8N3IcegpHGAFI4kbzWcqOqd8Vij9ZAc',
    appId: '1:698836614759:ios:038bee32c79ecf5e21dec2',
    messagingSenderId: '698836614759',
    projectId: 'chamgohae123',
    storageBucket: 'chamgohae123.appspot.com',
    iosBundleId: 'com.example.chamgohae1.RunnerTests',
  );
}
